_wandb:
    value:
        cli_version: 0.28.0
        e:
            n7c3xfdktf23wzgnjerm2jdpp735qz2m:
                apple:
                    ecpuCores: 6
                    gpuCores: 8
                    macModel: Mac16,12
                    memoryGb: 16
                    name: Apple M4
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "6442450944"
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "245107195904"
                        used: "198302126080"
                email: anshu.me.maan01@gmail.com
                executable: /Users/anshumaan-garg/Documents/Projects/Great Learning/ML_module_2/venv/bin/python
                host: Anshumaans-MacBook-Air.local
                memory:
                    total: "17179869184"
                os: macOS-26.1-arm64-arm-64bit-Mach-O
                program: -m src.train
                python: CPython 3.13.7
                root: /Users/anshumaan-garg/Documents/Projects/Great Learning/ML_module_2/personal_loan_camapaign
                startedAt: "2026-06-28T10:28:30.708430Z"
                writerId: n7c3xfdktf23wzgnjerm2jdpp735qz2m
        m: []
        python_version: 3.13.7
        t:
            "1":
                - 5
                - 35
                - 53
            "2":
                - 5
                - 35
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.13.7
            "5": 0.28.0
            "12": 0.28.0
            "13": darwin-arm64
class_weight:
    value: null
criterion:
    value: gini
max_depth:
    value: 3
min_samples_leaf:
    value: 16
min_samples_split:
    value: 11
