_wandb:
    value:
        cli_version: 0.28.0
        e:
            4pmxo4e2u86kw8irovij8flnee7sugxc:
                email: anshu.me.maan01@gmail.com
                executable: /Users/anshumaan-garg/Documents/Projects/Great Learning/ML_module_2/venv/bin/python
                host: Anshumaans-MacBook-Air.local
                os: macOS-26.1-arm64-arm-64bit-Mach-O
                program: -m src.train
                python: CPython 3.13.7
                root: /Users/anshumaan-garg/Documents/Projects/Great Learning/ML_module_2/personal_loan_camapaign
                startedAt: "2026-06-28T10:27:46.801404Z"
                writerId: 4pmxo4e2u86kw8irovij8flnee7sugxc
        m: []
        python_version: 3.13.7
        t:
            "1":
                - 5
                - 35
                - 53
            "2":
                - 5
                - 35
                - 53
            "3":
                - 2
                - 16
            "4": 3.13.7
            "5": 0.28.0
            "12": 0.28.0
            "13": darwin-arm64
class_weight:
    value: null
criterion:
    value: gini
max_depth:
    value: 3
min_samples_leaf:
    value: 11
min_samples_split:
    value: 23
